### ISSUE TITLE
Energy_demand minimal run looks for data in non-existing directory

### ISSUE THREAD

**Issue by RoaldL** [nismod/energy_demand#114]
The `smif run energy_demand_test` run looks for `/vagrant/data/energy_demand/_raw_data/K-floor_area/floor_area_2018_03_27.csv` while the `energy_demand minimal_setup` has created this file in  `/vagrant/data/energy_demand/_raw_data_minimal/K-floor_area/floor_area_2018_03_27.csv`

```
Traceback (most recent call last):
  File "/usr/local/bin/smif", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/smif/cli/__init__.py", line 623, in main
    args.func(args)
  File "/usr/local/lib/python3.5/dist-packages/smif/cli/__init__.py", line 435, in execute_model_run
    modelrun.run(store)
  File "/usr/local/lib/python3.5/dist-packages/smif/modelrun.py", line 118, in run
    modelrunner.solve_model(self, store)
  File "/usr/local/lib/python3.5/dist-packages/smif/modelrun.py", line 147, in solve_model
    model_run.sos_model.before_model_run(data_handle)
  File "/usr/local/lib/python3.5/dist-packages/smif/model/sos_model.py", line 114, in before_model_run
    model.before_model_run(model_data_handle)
  File "./models/energy_demand/run.py", line 180, in before_model_run
    f_mixed_floorarea=assumptions.f_mixed_floorarea)
  File "/usr/local/lib/python3.5/dist-packages/energy_demand/read_write/data_loader.py", line 162, in floor_area_virtual_dw
    f_mixed_floorarea=f_mixed_floorarea)
  File "/usr/local/lib/python3.5/dist-packages/energy_demand/read_write/read_data.py", line 1183, in read_floor_area_virtual_stock
    with open(path_to_csv, 'r') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: '/vagrant/data/energy_demand/_raw_data/K-floor_area/floor_area_2018_03_27.csv'
vagrant@vagrant:/vagrant$ 
```

**Comment by RoaldL** [comment]
Versions installed:
> energy_demand 0.4.2
smif 0.7.6

Configuration:
```
[energy-demand]
ftp_source=/data/energy_demand/v_042_minimum.zip
target=/vagrant/data/energy_demand
release=0.4.2
```

**Comment by eggimasv** [comment]
Both folders from the minimal and full setup needs to be called _raw_data. The data folder of the mininum_setup zip has been renamed.

**Comment by willu47** [comment]
Unfortunately, this has not been resolved. Unzipping v_042 of the data now results in the files placed under the directory: `v_XX_minimum`

**Comment by eggimasv** [comment]
hopefully fixed now. my fault
