### ISSUE TITLE
Cannot run on OSX due to matplotlib requirement

### ISSUE THREAD

**Issue by willu47** [nismod/energy_demand#167]
When trying to run the energy demand model using smif, I get the following error caused by the matplotlib requirement of the energy demand model.
```python
Traceback (most recent call last):
  File "/Users/will2/miniconda3/envs/smif/bin/smif", line 11, in <module>
    load_entry_point('smif', 'console_scripts', 'smif')()
  File "/Users/will2/repository/nismod2/smif/src/smif/cli/__init__.py", line 461, in main
    args.func(args)
  File "/Users/will2/repository/nismod2/smif/src/smif/cli/__init__.py", line 225, in run_model_runs
    execute_model_run(model_run_ids, store, args.warm)
  File "/Users/will2/repository/nismod2/smif/src/smif/controller/execute.py", line 19, in execute_model_run
    model_run_definitions.append(get_model_run_definition(store, model_run))
  File "/Users/will2/repository/nismod2/smif/src/smif/controller/build.py", line 40, in get_model_run_definition
    sector_models = get_sector_models(sos_model_config['sector_models'], store)
  File "/Users/will2/repository/nismod2/smif/src/smif/controller/build.py", line 107, in get_sector_models
    sector_model = loader.load(sector_model_config)
  File "/Users/will2/repository/nismod2/smif/src/smif/data_layer/model_loader.py", line 42, in load
    klass = self.load_model_class(config['name'], config['path'], config['classname'])
  File "/Users/will2/repository/nismod2/smif/src/smif/data_layer/model_loader.py", line 80, in load_model_class
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "models/energy_demand/run.py", line 10, in <module>
    from energy_demand import wrapper_model
  File "/Users/will2/repository/nismod2/energy_demand/energy_demand/wrapper_model.py", line 6, in <module>
    from energy_demand.read_write import data_loader
  File "/Users/will2/repository/nismod2/energy_demand/energy_demand/read_write/data_loader.py", line 13, in <module>
    import matplotlib.pyplot as plt
  File "/Users/will2/miniconda3/envs/smif/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2372, in <module>
    switch_backend(rcParams["backend"])
  File "/Users/will2/miniconda3/envs/smif/lib/python3.7/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/Users/will2/miniconda3/envs/smif/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/will2/miniconda3/envs/smif/lib/python3.7/site-packages/matplotlib/backends/backend_macosx.py", line 14, in <module>
    from matplotlib.backends import _macosx
ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.
```

**Comment by tomalrussell** [comment]
This looks like a known issue with matplotlib on OSX:
- matplotlib docs: [Working with Matplotlib on OSX](https://matplotlib.org/faq/osx_framework.html)

Ways to install and work with matplotlib on OSX in virtual environments:
- if pip installed, use `TkAgg` backend [[1]](https://stackoverflow.com/questions/31373163/anaconda-runtime-error-python-is-not-installed-as-a-framework/44912322#44912322)
  - Create `~/.matplotlib/matplotlibrc`
  - Add `backend: TkAgg` to the file.
- or try `conda install matplotlib` [[2]](https://stackoverflow.com/questions/31373163/anaconda-runtime-error-python-is-not-installed-as-a-framework/41433353#41433353)
